extends RefCounted

func run(a: RefCounted) -> bool:
	if not FileAccess.file_exists("res://presentation/input_gate.gd"):
		a.truth(false, "input gate implementation exists")
		return true
	var script = load("res://presentation/input_gate.gd")
	if script == null or not script.can_instantiate():
		a.truth(false, "input gate loads")
		return true
	var gate = script.new()
	a.truth(gate is RefCounted and not gate is Node, "input gate is independent of scene tree")
	a.equal(gate.release(0, "tile-a", "round-1"), {"ok": false, "code": "NO_CAPTURE"}, "release without deliberate press is rejected")
	gate.press(0, "tile-a", "round-1")
	a.equal(gate.release(0, "tile-a", "round-1"), {"ok": true, "code": "OK", "target_id": "tile-a", "round_id": "round-1"}, "same pointer target and round produces take intent on release")
	a.equal(gate.release(0, "tile-a", "round-1"), {"ok": false, "code": "NO_CAPTURE"}, "one press cannot emit a second take intent")
	gate.press(-1, "tile-a", "round-1")
	a.equal(gate.release(-1, "tile-b", "round-1"), {"ok": false, "code": "TARGET_MISMATCH"}, "press A release B cannot transfer the action")
	a.equal(gate.release(-1, "tile-a", "round-1"), {"ok": false, "code": "NO_CAPTURE"}, "mismatched target consumes the original gesture")
	gate.press(3, "tile-a", "round-1")
	a.equal(gate.release(3, "", "round-1"), {"ok": false, "code": "TARGET_MISMATCH"}, "release outside all hit regions cannot take a tile")
	gate.press(7, "tile-a", "round-2")
	a.equal(gate.release(8, "tile-a", "round-2"), {"ok": false, "code": "POINTER_MISMATCH"}, "unrelated release cannot activate the captured action")
	a.equal(gate.release(7, "tile-a", "round-1"), {"ok": false, "code": "ROUND_MISMATCH"}, "old round callback cannot activate a fresh capture")
	a.equal(gate.release(7, "tile-a", "round-2").get("ok"), true, "unrelated and old releases cannot consume a current capture")
	gate.press(9, "tile-a", "round-2")
	gate.press(9, "tile-b", "round-2")
	a.equal(gate.release(9, "tile-a", "round-2").get("target_id"), "tile-a", "duplicate press cannot replace immutable target identity")
	for identity in [["", "round-2"], ["tile-a", ""]]:
		gate.press(0, identity[0], identity[1])
		a.equal(gate.release(0, "tile-a", "round-2"), {"ok": false, "code": "NO_CAPTURE"}, "empty semantic target or round cannot arm input")
	if not gate.has_method("set_board_locked") or not gate.has_method("cancel_all"):
		a.truth(false, "input gate exposes lock and lifecycle cancellation")
		return true
	gate.set_board_locked(true)
	gate.press(1, "tile-a", "round-3")
	a.equal(gate.release(1, "tile-a", "round-3"), {"ok": false, "code": "BOARD_LOCKED"}, "locked board rejects deliberate click")
	gate.press(2, "tile-b", "round-3")
	gate.set_board_locked(false)
	a.equal(gate.release(2, "tile-b", "round-3"), {"ok": false, "code": "NO_CAPTURE"}, "unlock never queues a press received during animation")
	gate.press(1, "tile-a", "round-3")
	gate.set_board_locked(true)
	gate.set_board_locked(false)
	a.equal(gate.release(1, "tile-a", "round-3"), {"ok": false, "code": "NO_CAPTURE"}, "lock arising between press and release invalidates capture")
	gate.press(1, "tile-a", "round-3")
	gate.set_board_locked(false)
	a.equal(gate.release(1, "tile-a", "round-3").get("ok"), true, "redundant unlock does not cancel a valid fresh gesture")
	for reason in ["drag_out", "hidden", "resize", "modal", "exit", "next_round"]:
		gate.press(11, "tile-a", "round-3")
		gate.cancel_all(reason)
		gate.cancel_all(reason)
		a.equal(gate.release(11, "tile-a", "round-3"), {"ok": false, "code": "NO_CAPTURE"}, reason + " cancels instead of emitting a take intent")
		gate.press(11, "tile-a", "round-3")
		a.equal(gate.release(11, "tile-a", "round-3").get("ok"), true, reason + " cancellation does not poison the next deliberate gesture")
	gate.press(-1, "tile-a", "round-3")
	gate.set_board_locked(true)
	gate.cancel_all("modal")
	gate.press(-1, "tile-a", "round-3")
	a.equal(gate.release(-1, "tile-a", "round-3").get("code"), "BOARD_LOCKED", "modal cancellation cannot unlock underlying board")
	gate.set_board_locked(false)
	gate.press(4, "tile-a", "round-3")
	gate.cancel_all("next_round")
	gate.press(4, "tile-b", "round-4")
	a.equal(gate.release(4, "tile-a", "round-3").get("code"), "ROUND_MISMATCH", "old callback after round change cannot take old tile or discard new gesture")
	a.equal(gate.release(4, "tile-b", "round-4").get("target_id"), "tile-b", "fresh round remains operable after old callback")
	gate.press(4, "tile-b", "round-4")
	gate.press(5, "tile-a", "round-old")
	a.equal(gate.release(4, "tile-b", "round-4").get("target_id"), "tile-b", "old round press cannot cancel current capture")
	gate.release(5, "tile-a", "round-old")
	gate.press(4, "tile-a", "round-4")
	gate.press(5, "tile-b", "round-4")
	a.equal(gate.release(5, "tile-b", "round-4"), {"ok": false, "code": "NO_CAPTURE"}, "secondary pointer cannot take its own tile")
	a.equal(gate.release(4, "tile-a", "round-4"), {"ok": false, "code": "NO_CAPTURE"}, "second pointer cancels original captured gesture too")
	gate.press(4, "tile-a", "round-4")
	gate.press(5, "tile-b", "round-4")
	gate.press(6, "tile-c", "round-4")
	a.equal(gate.release(6, "tile-c", "round-4"), {"ok": false, "code": "NO_CAPTURE"}, "third pointer cannot recapture while multi-touch remains down")
	gate.release(4, "tile-a", "round-4")
	gate.release(5, "tile-b", "round-4")
	gate.press(42, "tile-c", "round-4")
	a.equal(gate.release(42, "tile-c", "round-4").get("ok"), true, "fresh arbitrary touch ID works after all pointers release")
	return true
