'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../src/commerce/model');
const cfg=require('../config/commerce.v010.json');
const ctx=(more={})=>({placement:'move',roundId:'r1',boardRevision:5,used:0,effectReady:true,phase:'PLAYING',mode:'simulation',...more});
const flow=()=>M.createFlow({id:'f1',roundId:'r1',placement:'move',boardRevision:5,dayKey:'2026-09-18',configVersion:'commerce-v010'});
const step=(f,kind,more={})=>M.advance(f,{id:'e'+(f.events.length+1),kind,at:1000+f.events.length,...more}).flow;
const showing=()=>['ACCEPT','AD_READY','SHOW'].reduce((f,k)=>step(f,k),flow());
const earned=()=>step(showing(),'AD_CLOSE',{isEnded:true});
test('commercial preflight permits a valid simulated move',()=>assert.equal(M.decideOffer(ctx(),cfg).allowed,true));
test('production gate remains closed without real approval and credentials',()=>assert.equal(M.decideOffer(ctx({mode:'production'}),cfg).allowed,false));
test('unbound revive is rejected before requesting an advertisement',()=>assert.equal(M.decideOffer(ctx({placement:'revive',phase:'LOST'}),cfg).reason,'EFFECT_UNBOUND'));
test('no assist opportunity after its round allowance is used',()=>assert.equal(M.decideOffer(ctx({used:1}),cfg).reason,'ROUND_LIMIT'));
test('board preflight failure cannot display a reward offer',()=>assert.equal(M.decideOffer(ctx({effectReady:false}),cfg).reason,'EFFECT_NOT_APPLICABLE'));
test('no fabricated daily allowance: null means no product cap assigned',()=>assert.equal(cfg.dailyProductCap,null));
test('unknown placement never falls through to a real ad slot',()=>assert.equal(M.decideOffer(ctx({placement:'purchase'}),cfg).allowed,false));
test('malformed used count is rejected rather than bypassing allowance',()=>assert.equal(M.decideOffer(ctx({used:-1}),cfg).allowed,false));
test('normal flow separates complete evidence from reward application',()=>{let f=earned();assert.equal(f.state,'EARNED_PENDING');assert.equal(M.summarizeFlows([f]).grants,0);f=step(f,'GRANT_COMMITTED',{roundId:'r1',beforeRevision:5});assert.equal(f.state,'APPLIED');f=step(f,'PLAY_RESUMED',{roundId:'r1'});assert.equal(f.state,'RESUMED');});
test('a closed but incomplete ad grants nothing',()=>assert.equal(step(showing(),'AD_CLOSE',{isEnded:false}).state,'CANCELLED'));
test('missing completion flag is unresolved, not a free reward',()=>assert.equal(step(showing(),'AD_CLOSE').state,'UNVERIFIED'));
test('ordinary share return cannot masquerade as ad completion',()=>assert.equal(step(showing(),'SHARE_RETURN').state,'UNVERIFIED'));
test('duplicate event is idempotent',()=>{const e={id:'close',kind:'AD_CLOSE',isEnded:true,at:5000},a=M.advance(showing(),e),b=M.advance(a.flow,e);assert.equal(b.replayed,true);assert.deepEqual(a.flow,b.flow);});
test('same event id with different data is rejected',()=>{const e={id:'close',kind:'AD_CLOSE',isEnded:true,at:5000},a=M.advance(showing(),e);assert.throws(()=>M.advance(a.flow,{...e,isEnded:false}),/EVENT_ID_CONFLICT/);});
test('ad cannot complete without a show attempt',()=>assert.throws(()=>M.advance(flow(),{id:'e1',kind:'AD_CLOSE',isEnded:true,at:0}),/INVALID_TRANSITION/));
test('failed grant retains earned entitlement for retry without another ad',()=>{let f=step(earned(),'GRANT_FAILED');assert.equal(f.state,'RECOVERY_REQUIRED');f=step(f,'GRANT_COMMITTED',{roundId:'r1',beforeRevision:5});assert.equal(f.state,'APPLIED');assert.equal(M.summarizeFlows([f]).optedIn,1);});
test('old round completion cannot reward a different round',()=>{const f=step(earned(),'GRANT_COMMITTED',{roundId:'r2',beforeRevision:5});assert.equal(f.state,'RECOVERY_REQUIRED');assert.equal(M.summarizeFlows([f]).grants,0);});
test('changed board revision cannot commit stale reward',()=>assert.equal(step(earned(),'GRANT_COMMITTED',{roundId:'r1',beforeRevision:6}).state,'RECOVERY_REQUIRED'));
test('load failure is recorded without spending a round use',()=>{const f=step(step(flow(),'ACCEPT'),'AD_FAILED');assert.equal(f.state,'FAILED');assert.equal(M.summarizeFlows([f]).grants,0);});
test('duplicate grants with new event id are rejected',()=>{const f=step(earned(),'GRANT_COMMITTED',{roundId:'r1',beforeRevision:5});assert.throws(()=>step(f,'GRANT_COMMITTED',{roundId:'r1',beforeRevision:5}),/INVALID_TRANSITION/);});
test('ordinary successful pipeline has explicit denominators',()=>{let f=step(earned(),'GRANT_COMMITTED',{roundId:'r1',beforeRevision:5});f=step(f,'PLAY_RESUMED',{roundId:'r1'});const m=M.summarizeFlows([f]);assert.equal(m.offers,1);assert.equal(m.observedComplete,1);assert.equal(m.grants,1);assert.equal(m.resumed,1);assert.equal(m.grantRate,1);assert.equal(m.revenueCny,null);});
test('funnel does not guess zero revenue or completion rate with no data',()=>{const m=M.summarizeFlows([]);assert.equal(m.completionRate,null);assert.equal(m.revenueCny,null);});
test('duplicate flow records are rejected rather than double counted',()=>assert.throws(()=>M.summarizeFlows([flow(),flow()]),/DUPLICATE_FLOW/));
test('report separates estimated settled and cash values, no second revenue share',()=>{const r=M.reconcile({currency:'CNY',timezone:'Asia/Shanghai',status:'partial',platformImpressions:3000,estimatedNetFen:6000,settledNetFen:5000,cashReceivedFen:4000,paidTrafficFen:1000,variableCostFen:500});assert.equal(r.ecpmNetCny,20);assert.equal(r.settledContributionCny,35);assert.equal(r.cashReceivedCny,40);assert.equal(r.estimatedNetCny,60);assert.equal(r.status,'partial');});
test('zero is a reported value; null is missing information',()=>{const r=M.reconcile({currency:'CNY',timezone:'Asia/Shanghai',status:'final',platformImpressions:0,estimatedNetFen:0,settledNetFen:null,cashReceivedFen:null,paidTrafficFen:0,variableCostFen:0});assert.equal(r.estimatedNetCny,0);assert.equal(r.ecpmNetCny,null);assert.equal(r.settledContributionCny,null);});
test('monetary inputs use integer fen and explicit currency',()=>{assert.throws(()=>M.reconcile({currency:'USD'}),/CURRENCY/);assert.throws(()=>M.reconcile({currency:'CNY',timezone:'Asia/Shanghai',status:'final',estimatedNetFen:0.5}),/INTEGER_FEN/);});
test('round state and algorithm files are not mutated by ledger',()=>{const f=showing(),copy=JSON.stringify(f);step(f,'AD_CLOSE',{isEnded:true});assert.equal(JSON.stringify(f),copy);});
test('documented config has no purchase entry or invented banner',()=>{assert.equal(cfg.purchaseEnabled,false);assert.deepEqual(cfg.adFormats,['rewarded_video']);assert.equal(cfg.shareRewardEnabled,false);});
