'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const api=fs.existsSync(path.join(__dirname,'../src/integration/controller.js'))?require('../src/integration/controller'):{};
const deal=require('../examples/deal-270.json');
function store(){let text=null,fail=false;return {read:()=>text,write:x=>{if(fail)throw Error('disk unavailable');text=x;},setFail:x=>fail=x};}
function boot(storage=store()){assert.equal(typeof api.createController,'function','controller missing');const c=api.createController(deal,{roundId:'c1',storage});return {c,storage};}
function shuffle(c){assert.ok(c.request('shuffle').ok);assert.ok(c.choose('ad').ok);return c.view().activeFlowId;}
test('controller: successful application persists and restores same actual state',()=>{const {c,storage}=boot(),id=shuffle(c);assert.ok(c.receive({flowId:id,roundId:'c1',kind:'ad_closed',isEnded:true}).ok);assert.ok(c.apply().ok);const n=api.restoreController(storage.read(),{storage});assert.equal(n.view().session.used.shuffle,1);assert.equal(n.view().session.board.deal.snapshotHash,c.view().session.board.deal.snapshotHash);});
test('controller: earning during disk failure retained in memory, not applied',()=>{const {c,storage}=boot(),id=shuffle(c);storage.setFail(true);const r=c.receive({flowId:id,roundId:'c1',kind:'ad_closed',isEnded:true});assert.equal(r.ok,true);assert.equal(r.saved,false);assert.equal(c.apply().ok,false);assert.equal(c.view().session.used.shuffle,0);storage.setFail(false);assert.equal(c.apply().ok,true);assert.equal(c.view().session.used.shuffle,1);});
test('controller: failed grant persistence leaves pending entitlement and no charged quota',()=>{const {c,storage}=boot(),id=shuffle(c);c.receive({flowId:id,roundId:'c1',kind:'ad_closed',isEnded:true});storage.setFail(true);assert.equal(c.apply().ok,false);assert.equal(c.view().session.used.shuffle,0);storage.setFail(false);assert.ok(c.apply().ok);assert.equal(c.view().session.used.shuffle,1);});
test('controller: explicit restore of awaiting video never assumes completion',()=>{const {c,storage}=boot();shuffle(c);const n=api.restoreController(storage.read(),{storage});assert.equal(n.view().session.used.shuffle,0);assert.equal(n.view().flows[0].status,'AWAITING_PROVIDER');});
test('controller: restart rejects late callback from previous round',()=>{const {c}=boot(),id=shuffle(c);const n=api.createController(deal,{roundId:'c2'});assert.equal(n.receive({flowId:id,roundId:'c1',kind:'ad_closed',isEnded:true}).code,'WRONG_ROUND');assert.equal(n.view().session.used.shuffle,0);});
test('controller: getter cannot mutate live session',()=>{const {c}=boot(),v=c.view();v.session.used.move=100;assert.equal(c.view().session.used.move,0);});
test('controller: no raw storage data is executed on restore',()=>{boot();assert.throws(()=>api.restoreController('bad'),/INVALID_LOG/);});
test('controller: explicit injected application failure then retry uses original permutation',()=>{const {c}=boot(),id=shuffle(c);c.receive({flowId:id,roundId:'c1',kind:'ad_closed',isEnded:true});const p=c.view().flows[0].permutation;c.failApplication();assert.equal(c.view().flows[0].status,'RECOVERY_REQUIRED');assert.ok(c.apply().ok);assert.deepEqual(c.view().session.commands.at(-1).permutation,p);});
test('controller: local ledger refuses production',()=>{boot();assert.throws(()=>api.createController(deal,{roundId:'prod',mode:'production'}),/PRODUCTION/);});
test('controller: unbound revive does not create any request',()=>{const {c}=boot();assert.equal(c.request('revive').code,'REVIVE_RULE_UNBOUND');assert.equal(c.view().flows.length,0);});

test('controller: result object cannot mutate live entitlement or board',()=>{const {c}=boot();const r=c.request('shuffle');r.state.session.used.shuffle=50;r.state.flows[0].status='APPLIED';assert.equal(c.view().session.used.shuffle,0);assert.equal(c.view().flows[0].status,'OFFERED');});
