'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const S=require('../src/play/session');
function deal(){return {schema:'astra-deal-1',dealId:'f',layoutId:'f',slotCapacity:7,cells:[...'ABCABCABC'].map((type,i)=>({id:'t'+i,type,zone:'board',z:0,rect:{x:i*110,y:0,w:100,h:100}}))};}
function start(d=deal()){return S.createSession(d,{roundId:'r',rewardMode:'development_mock'});}
function step(s,type,rest={}){const command={id:'c'+s.revision,roundId:'r',expectedRevision:s.revision,type,...rest},r=S.dispatch(s,command);assert.equal(r.ok,true,r.code);return {s:r.session,command};}
test('play hardening: optional undefined input is normalized consistently across replay',()=>{let s=step(start(),'REQUEST_ASSIST',{assist:'shuffle'}).s;const c={id:'result',roundId:'r',expectedRevision:s.revision,type:'REWARD_RESULT',token:s.pending.token,result:'cancelled',permutation:undefined};s=S.dispatch(s,c).session;const restored=S.restoreSession(S.exportSession(s));assert.equal(restored.ok,true);const ack=S.dispatch(restored.session,c);assert.equal(ack.ok,true,ack.code);assert.equal(ack.replayed,true);});
test('play hardening: legal long tile ID supported by approved snapshot remains playable',()=>{const d=deal();d.cells[0].id='x'.repeat(180);const s=start(d),r=S.dispatch(s,{id:'c0',roundId:'r',expectedRevision:0,type:'PICK',tileId:d.cells[0].id});assert.equal(r.ok,true,r.code);});
test('play hardening: exhausted undo cannot be reacquired after another pick',()=>{let s=step(start(),'PICK',{tileId:'t0'}).s;s=step(s,'REQUEST_ASSIST',{assist:'undo'}).s;s=step(s,'REWARD_RESULT',{token:s.pending.token,result:'completed'}).s;s=step(s,'PICK',{tileId:'t1'}).s;assert.equal(S.dispatch(s,{id:'another',roundId:'r',expectedRevision:s.revision,type:'REQUEST_ASSIST',assist:'undo'}).code,'ASSIST_EXHAUSTED');});
test('play hardening: exhausted shuffle cannot be reacquired',()=>{let s=step(start(),'REQUEST_ASSIST',{assist:'shuffle'}).s;s=step(s,'REWARD_RESULT',{token:s.pending.token,result:'completed',permutation:s.board.deal.cells.map(c=>c.type)}).s;assert.equal(S.dispatch(s,{id:'another',roundId:'r',expectedRevision:s.revision,type:'REQUEST_ASSIST',assist:'shuffle'}).code,'ASSIST_EXHAUSTED');});
test('play hardening: pending modal cannot be reopened by delayed duplicate request',()=>{const r=step(start(),'REQUEST_ASSIST',{assist:'shuffle'});let s=step(r.s,'REWARD_RESULT',{token:r.s.pending.token,result:'cancelled'}).s;const ack=S.dispatch(s,r.command);assert.equal(ack.replayed,true);assert.equal(ack.session.pending,null);});
test('play hardening: prototype-looking IDs cannot modify session dictionaries',()=>{const s=start(),r=S.dispatch(s,{id:'__proto__',roundId:'r',expectedRevision:0,type:'PICK',tileId:'t0'});assert.equal(r.ok,true);assert.equal(Object.getPrototypeOf(r.session.receipts),null);assert.equal(S.dispatch(r.session,{id:'__proto__',roundId:'r',expectedRevision:0,type:'PICK',tileId:'t0'}).replayed,true);});
test('play hardening: all approved algorithm files remain byte-identical to v0.8',()=>{const root=path.join(__dirname,'..'),m=JSON.parse(fs.readFileSync(path.join(root,'docs/v0.8_algorithm_frozen.json')));for(const [file,hash] of Object.entries(m))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),hash,file);});
test('play hardening: WeChat copies exactly match all tested gameplay sources',()=>{const root=path.join(__dirname,'..');for(const file of ['src/runtime.js','src/layout.js','src/schema.js','src/content-hash.js','src/play/profile.js','src/play/board.js','src/play/session.js','src/play/shuffle.js','ui/play-app.js'])assert.deepEqual(fs.readFileSync(path.join(root,file)),fs.readFileSync(path.join(root,'wechat_game',file)),file);});
test('play hardening: new browser and WeChat deal do not contain private witness',()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'道具与对局联调_双击打开.html'),'utf8'),data=require('../wechat_game/data/deal');assert.equal('witness' in data,false);assert.equal(html.includes('"witness":'),false);});
