'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const api=fs.existsSync(path.join(__dirname,'../src/play/session.js'))?require('../src/play/session'):{};
function deal(){return {schema:'astra-deal-1',dealId:'fixture',layoutId:'open',origin:'SYNTHETIC_NOT_HISTORICAL',slotCapacity:7,cells:[...'ABCABCABC'].map((type,i)=>({id:'t'+i,type,zone:'board',z:0,rect:{x:i*110,y:0,w:100,h:100}}))};}
function boot(roundId='r1'){assert.equal(typeof api.createSession,'function','session module not implemented');return api.createSession(deal(),{roundId,rewardMode:'development_mock'});}
function cmd(s,type,rest={}){return {id:'c'+s.revision,roundId:s.roundId,expectedRevision:s.revision,type,...rest};}
function step(s,type,data={}){const r=api.dispatch(s,cmd(s,type,data));assert.equal(r.ok,true,r.code);return r.session;}
function rack3(){let s=boot();for(const tileId of ['t0','t1','t2'])s=step(s,'PICK',{tileId});return s;}
function request(s,assist){return step(s,'REQUEST_ASSIST',{assist});}
function outcome(s,result,more={}){return step(s,'REWARD_RESULT',{token:s.pending.token,result,...more});}
test('session: use of the development reward mode is explicit',()=>{assert.throws(()=>api.createSession(deal(),{roundId:'r1',rewardMode:'live'}));boot();});
test('session: request reserves eligibility without consuming quota or changing cards',()=>{const s=rack3(),n=request(s,'move');assert.equal(n.used.move,0);assert.equal(n.board,s.board);assert.equal(n.pending.assist,'move');});
test('session: completed mock reward applies the effect and quota in one commit',()=>{const s=outcome(request(rack3(),'move'),'completed');assert.equal(s.used.move,1);assert.equal(s.board.buffer.length,3);assert.equal(s.pending,null);});
for(const result of ['cancelled','failed','share_returned'])test('session: '+result+' never grants reward or consumes quota',()=>{const s=rack3(),n=outcome(request(s,'move'),result);assert.equal(n.used.move,0);assert.deepEqual(n.board,s.board);assert.equal(n.pending,null);});
test('session: request is preflighted before showing any mock advert',()=>{const s=boot(),r=api.dispatch(s,cmd(s,'REQUEST_ASSIST',{assist:'move'}));assert.equal(r.code,'NOT_ENOUGH_RACK_TILES');assert.equal(r.session,s);});
test('session: revive is unbound before reward UI is opened',()=>{const s=boot(),r=api.dispatch(s,cmd(s,'REQUEST_ASSIST',{assist:'revive'}));assert.equal(r.code,'REVIVE_RULE_UNBOUND');assert.equal(r.session.pending,null);});
test('session: picks are locked while reward is pending',()=>{const s=request(rack3(),'move'),r=api.dispatch(s,cmd(s,'PICK',{tileId:'t3'}));assert.equal(r.code,'REWARD_PENDING');assert.equal(r.session,s);});
test('session: second concurrent assist request is rejected',()=>{const s=request(rack3(),'move');assert.equal(api.dispatch(s,cmd(s,'REQUEST_ASSIST',{assist:'shuffle'})).code,'REWARD_PENDING');});
test('session: each of the three assists can be consumed at most once per round',()=>{let s=outcome(request(rack3(),'move'),'completed');for(const tileId of ['t3','t4','t5'])s=step(s,'PICK',{tileId});assert.equal(api.dispatch(s,cmd(s,'REQUEST_ASSIST',{assist:'move'})).code,'ASSIST_EXHAUSTED');});
test('session: duplicate command returns acknowledgement without repeated events',()=>{const s=boot(),c=cmd(s,'PICK',{tileId:'t0'}),r=api.dispatch(s,c),dup=api.dispatch(r.session,c);assert.equal(dup.ok,true);assert.equal(dup.replayed,true);assert.equal(dup.session,r.session);assert.deepEqual(dup.events,[]);});
test('session: same command ID with different payload is rejected',()=>{const s=boot(),c=cmd(s,'PICK',{tileId:'t0'}),r=api.dispatch(s,c);assert.equal(api.dispatch(r.session,{...c,tileId:'t1'}).code,'COMMAND_ID_CONFLICT');});
test('session: stale revision is rejected before any card change',()=>{const s=step(boot(),'PICK',{tileId:'t0'});assert.equal(api.dispatch(s,{...cmd(s,'PICK',{tileId:'t1'}),expectedRevision:0}).code,'STALE_REVISION');});
test('session: old round callback cannot affect a new round',()=>{const s=request(rack3(),'move'),fresh=boot('r2'),r=api.dispatch(fresh,{...cmd(s,'REWARD_RESULT',{token:s.pending.token,result:'completed'}),expectedRevision:0});assert.equal(r.code,'WRONG_ROUND');assert.equal(r.session,fresh);});
test('session: wrong reward token does not clear pending request',()=>{const s=request(rack3(),'move');assert.equal(api.dispatch(s,cmd(s,'REWARD_RESULT',{token:'bad',result:'completed'})).code,'WRONG_REWARD_TOKEN');});
test('session: same reward token under a different command ID cannot grant twice',()=>{const p=request(rack3(),'move'),token=p.pending.token,s=outcome(p,'completed');const r=api.dispatch(s,cmd(s,'REWARD_RESULT',{token,result:'completed'}));assert.equal(r.code,'REWARD_ALREADY_RESOLVED');assert.equal(r.session.used.move,1);});
test('session: invalid shuffle payload leaves board, quota and pending token untouched',()=>{const s=request(boot(),'shuffle'),r=api.dispatch(s,cmd(s,'REWARD_RESULT',{token:s.pending.token,result:'completed',permutation:['A']}));assert.equal(r.ok,false);assert.equal(r.session,s);assert.equal(s.used.shuffle,0);});
test('session: shuffle success stores actual permutation in replay log',()=>{const s=request(boot(),'shuffle'),permutation=s.board.deal.cells.map(c=>c.type).reverse(),n=outcome(s,'completed',{permutation});assert.deepEqual(n.commands.at(-1).permutation,permutation);assert.equal(n.used.shuffle,1);});
test('session: all accepted operations survive diagnostic export/replay identically',()=>{let s=rack3();s=outcome(request(s,'move'),'completed');s=step(s,'PICK',{tileId:'t0'});s=outcome(request(s,'shuffle'),'completed',{permutation:s.board.deal.cells.filter((c,i)=>!s.board.taken[i]).map(c=>c.type).reverse()});const text=api.exportSession(s),r=api.restoreSession(text);assert.equal(r.ok,true,r.code);assert.equal(api.fingerprint(r.session),api.fingerprint(s));});
test('session: exporting a pending reward never grants it on restore',()=>{const s=request(rack3(),'move'),r=api.restoreSession(api.exportSession(s));assert.equal(r.ok,true);assert.equal(r.session.used.move,0);assert.equal(r.session.pending.token,s.pending.token);});
test('session: corrupted log checksum is rejected',()=>{const text=api.exportSession(boot()),e=JSON.parse(text);e.payload.roundId='wrong';assert.equal(api.restoreSession(JSON.stringify(e)).ok,false);});
test('session: malformed restore input is rejected safely',()=>{boot();assert.equal(api.restoreSession('not JSON').ok,false);});
test('session: duplicate reward callback remains idempotent after restore',()=>{const p=request(rack3(),'move'),c=cmd(p,'REWARD_RESULT',{token:p.pending.token,result:'completed'}),s=api.dispatch(p,c).session,r=api.restoreSession(api.exportSession(s));const d=api.dispatch(r.session,c);assert.equal(d.replayed,true);assert.equal(d.session.used.move,1);});
test('session: action payload is copied so caller mutation cannot corrupt replay',()=>{const s=boot(),c=cmd(s,'PICK',{tileId:'t0'}),r=api.dispatch(s,c);c.tileId='t1';assert.equal(r.session.commands[0].tileId,'t0');});
test('session: malformed request schema fails without accepting hidden extra fields',()=>{const s=boot();assert.equal(api.dispatch(s,{...cmd(s,'PICK',{tileId:'t0'}),cheat:true}).code,'INVALID_COMMAND');});
