'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const api=fs.existsSync(path.join(__dirname,'../src/play/board.js'))?require('../src/play/board'):{};
const profile={id:'community-working-v03',bufferReturn:'any',undoSources:['board'],clearUndoAfterAssist:true,reviveEffect:null};
function deal(labels=['A','B','C','A','B','C','A','B','C']){return {schema:'astra-deal-1',dealId:'fixture',layoutId:'open',origin:'SYNTHETIC_NOT_HISTORICAL',slotCapacity:7,cells:labels.map((type,i)=>({id:`t${i}`,type,zone:'board',z:0,rect:{x:i*110,y:0,w:100,h:100}}))};}
function boot(d=deal()){assert.equal(typeof api.createPlayRound,'function','play runtime not implemented');return api.createPlayRound(d,'round-1');}
function pick(s,id){const r=api.pickTile(s,id,profile);assert.equal(r.ok,true,r.code);return r.state;}
function assist(s,kind,labels){const r=api.applyAssist(s,kind,profile,labels);assert.equal(r.ok,true,r.code);return r.state;}
test('play: initial round preserves full card count and empty temporary area',()=>{const s=boot();assert.deepEqual(s.buffer,[]);assert.equal(api.checkRound(s),true);});
test('play: moving takes first three in current grouped rack order, not click order',()=>{let s=boot();for(const id of ['t0','t1','t3','t2'])s=pick(s,id);assert.deepEqual(s.rack,['t0','t3','t1','t2']);const before=JSON.stringify(s);const n=assist(s,'move');assert.deepEqual(n.buffer,['t0','t3','t1']);assert.deepEqual(n.rack,['t2']);assert.equal(n.cleared,0);assert.equal(JSON.stringify(s),before);});
test('play: fewer than three cards rejects move with no mutation',()=>{let s=pick(boot(),'t0');const r=api.applyAssist(s,'move',profile);assert.equal(r.code,'NOT_ENOUGH_RACK_TILES');assert.equal(r.state,s);});
test('play: buffer can return to rack and participate in triples',()=>{let s=boot();for(const id of ['t0','t1','t2'])s=pick(s,id);s=assist(s,'move');for(const id of ['t1','t4','t7'])s=pick(s,id);assert.equal(s.cleared,3);assert.deepEqual(s.buffer,['t0','t2']);assert.equal(api.checkRound(s),true);});
test('play: a returned buffer card cannot be picked twice',()=>{let s=boot();for(const id of ['t0','t1','t2'])s=pick(s,id);s=assist(s,'move');s=pick(s,'t0');assert.equal(api.pickTile(s,'t0',profile).code,'ALREADY_TAKEN');});
test('play: win waits for buffer and rack to be fully eliminated',()=>{let s=boot();for(const id of ['t0','t1','t2'])s=pick(s,id);s=assist(s,'move');for(const id of ['t3','t6','t4','t7','t5','t8'])s=pick(s,id);assert.notEqual(s.status,'WON');for(const id of ['t0','t1','t2'])s=pick(s,id);assert.equal(s.status,'WON');assert.equal(s.cleared,9);assert.deepEqual(s.buffer,[]);});
test('play: undo restores exact original position and blocker relationships',()=>{const d=deal(['A','A','A']);d.cells.forEach((c,i)=>{c.z=i;c.rect.x=0;});let s=boot(d);s=pick(s,'t2');assert.ok(api.legalTiles(s).includes('t1'));s=assist(s,'undo');assert.deepEqual(api.legalTiles(s),['t2']);assert.deepEqual(s.rack,[]);});
test('play: triple clears undo eligibility instead of resurrecting three tiles',()=>{let s=boot();for(const id of ['t0','t3','t6'])s=pick(s,id);assert.equal(api.canAssist(s,'undo',profile),'NO_UNDO');});
test('play: blocked picks do not overwrite the latest valid undo target',()=>{const d=deal();d.cells[3].rect={...d.cells[0].rect};d.cells[3].z=1;let s=pick(boot(d),'t1');const r=api.pickTile(s,'t0',profile);assert.equal(r.code,'BLOCKED');assert.equal(r.state,s);assert.equal(assist(s,'undo').rack.length,0);});
test('play: unverified side-stack undo is rejected rather than guessed',()=>{const d=deal(['A','A','A']);d.cells.forEach((c,i)=>{c.zone='side';c.stackId='s';c.position=i;delete c.z;});const s=pick(boot(d),'t0');assert.equal(api.canAssist(s,'undo',profile),'UNDO_SOURCE_UNBOUND');});
test('play: unverified buffer undo is rejected rather than guessed',()=>{let s=boot();for(const id of ['t0','t1','t2'])s=pick(s,id);s=assist(s,'move');s=pick(s,'t0');assert.equal(api.canAssist(s,'undo',profile),'UNDO_SOURCE_UNBOUND');});
test('play: move clears prior undo target under the explicit candidate profile',()=>{let s=boot();for(const id of ['t0','t1','t2'])s=pick(s,id);s=assist(s,'move');assert.equal(api.canAssist(s,'undo',profile),'NO_UNDO');});
test('play: shuffle leaves rack and buffer labels unchanged and records real mapping',()=>{let s=boot();for(const id of ['t0','t1','t2'])s=pick(s,id);s=assist(s,'move');s=pick(s,'t3');const labels=s.deal.cells.filter((c,i)=>!s.taken[i]).map(c=>c.type).reverse();const n=assist(s,'shuffle',labels);for(const id of [...s.rack,...s.buffer])assert.equal(n.deal.cells[n.byId[id]].type,s.deal.cells[s.byId[id]].type);assert.deepEqual(n.buffer,s.buffer);assert.equal(api.checkRound(n),true);assert.equal(n.shuffleOrdinal,1);});
test('play: bad shuffle permutation is refused atomically',()=>{const s=boot(),r=api.applyAssist(s,'shuffle',profile,['BAD']);assert.equal(r.code,'INVALID_SHUFFLE_PERMUTATION');assert.equal(r.state,s);});
test('play: identity permutation remains valid without secret re-roll',()=>{const s=boot(),n=assist(s,'shuffle',s.deal.cells.map(c=>c.type));assert.equal(n.deal.snapshotHash,s.deal.snapshotHash);assert.equal(n.revision,s.revision+1);});
test('play: revive effect is explicitly unbound',()=>{assert.equal(api.canAssist(boot(),'revive',profile),'REVIVE_RULE_UNBOUND');});
test('play: sixth-to-seventh matching card eliminates before losing',()=>{let s=boot(deal(['A','A','B','C','D','E','A','B','B','C','C','D','D','E','E']));for(let i=0;i<7;i++)s=pick(s,'t'+i);assert.equal(s.rack.length,4);assert.equal(s.status,'PLAYING');});
test('play: non-matching seventh card enters LOST and locks ordinary assists',()=>{let s=boot(deal([...('ABCDEFG'.repeat(3))]));for(let i=0;i<7;i++)s=pick(s,'t'+i);assert.equal(s.status,'LOST');assert.equal(api.canAssist(s,'move',profile),'ROUND_NOT_PLAYING');assert.equal(api.pickTile(s,'t7',profile).code,'ROUND_NOT_PLAYING');});
test('play: duplicate tile in buffer is caught by the invariant checker',()=>{const s=boot();assert.throws(()=>api.checkRound({...s,buffer:['t0','t0']}));});
test('play: tampered blocker counts are caught independently',()=>{const s=boot();assert.throws(()=>api.checkRound({...s,blockers:s.blockers.map(()=>1)}));});
module.exports={deal};
