'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const load=p=>fs.existsSync(require('node:path').join(__dirname,'..',p+'.js'))?require('../'+p):{};
const R=load('src/product/round'),C=load('src/product/controller'),Clock=load('src/product/clock');
function fixture(){return {schema:'astra-deal-1',dealId:'test',layoutId:'open',origin:'SYNTHETIC_NOT_HISTORICAL',slotCapacity:7,cells:[...'ABCDEFGHIJABCDEFGHIJABCDEFGHIJ'].map((type,i)=>({id:'t'+i,type,zone:'board',z:0,rect:{x:i%10*100,y:Math.floor(i/10)*100,w:96,h:96}}))};}
function boot(options={}){assert.equal(typeof C.createController,'function','product controller missing');return C.createController(fixture(),{roundId:'r1',...options});}
function earn(c,assist,channel='video'){assert.equal(c.offer(assist,channel).ok,true);assert.equal(c.launch().ok,true);const s=c.get();if(channel==='share'){assert.equal(c.result({roundId:s.roundId,token:s.pending.token,kind:'share_hide'}).ok,true);}assert.equal(c.result({roundId:s.roundId,token:s.pending.token,kind:channel==='share'?'share_return':'ad_close',isEnded:channel==='video'?true:undefined}).ok,true);return c.apply();}
test('product: new round is playable and production is rejected',()=>{assert.equal(boot().get().board.status,'PLAYING');assert.throws(()=>boot({mode:'production'}));});
test('product: revival moves three without deleting or reshuffling',()=>{const c=boot();for(let i=0;i<7;i++)assert.ok(c.pick('t'+i).ok);assert.equal(c.get().board.status,'LOST');assert.ok(earn(c,'revive').ok);const s=c.get();assert.equal(s.board.rack.length,4);assert.equal(s.board.buffer.length,3);assert.equal(s.board.cleared,0);assert.equal(s.used.revive,1);assert.equal(s.board.status,'PLAYING');});
test('product: revival preserves existing reserve and snapshot replays',()=>{const c=boot();for(let i=0;i<3;i++)c.pick('t'+i);assert.ok(earn(c,'move','share').ok);for(let i=3;i<10;i++)c.pick('t'+i);assert.ok(earn(c,'revive').ok);assert.deepEqual(c.get().board.buffer,['t0','t1','t2','t3','t4','t5']);assert.equal(R.restore(c.export()).ok,true);assert.ok(c.pick('t0').ok);assert.equal(c.get().board.buffer.length,5);});
test('product: premature ad close cannot grant',()=>{const c=boot();c.pick('t0');c.offer('undo','video');c.launch();const s=c.get();c.result({roundId:s.roundId,token:s.pending.token,kind:'ad_close',isEnded:false});assert.equal(c.get().used.undo,0);assert.equal(c.get().board.rack.length,1);assert.equal(c.apply().ok,false);});
test('product: an unqualified share return cannot grant',()=>{const c=boot();c.pick('t0');c.offer('undo','share');c.launch();const s=c.get();assert.equal(c.result({roundId:s.roundId,token:s.pending.token,kind:'share_return'}).ok,false);assert.equal(c.get().used.undo,0);});
test('product: old round and duplicate callbacks cannot apply twice',()=>{const c=boot();c.pick('t0');c.offer('undo','video');c.launch();const s=c.get();assert.equal(c.result({roundId:'old',token:s.pending.token,kind:'ad_close',isEnded:true}).ok,false);const e={roundId:s.roundId,token:s.pending.token,kind:'ad_close',isEnded:true};assert.ok(c.result(e).ok);assert.ok(c.apply().ok);assert.equal(c.result(e).ok,false);assert.equal(c.get().used.undo,1);});
test('product: ordinary persistence failure rolls command back',()=>{let fail=false;const c=boot({store:{write(){if(fail)throw Error('disk full');}}});fail=true;const s=c.get();assert.equal(c.pick('t0').ok,false);assert.deepEqual(c.get(),s);});
test('product: earned evidence is retained in memory, cannot apply until durable',()=>{let fail=false,saved;const c=boot({store:{write(v){if(fail)throw Error('disk full');saved=v;}}});c.pick('t0');c.offer('undo','video');c.launch();const s=c.get();fail=true;c.result({roundId:s.roundId,token:s.pending.token,kind:'ad_close',isEnded:true});assert.equal(c.get().pending.phase,'EARNED');assert.equal(c.apply().ok,false);assert.equal(c.get().used.undo,0);fail=false;assert.ok(c.flush().ok);assert.ok(c.apply().ok);assert.equal(R.restore(saved).state.used.undo,1);});
test('product: restore interrupts waiting but retries earned without another ad',()=>{const c=boot();c.pick('t0');c.offer('undo','video');c.launch();assert.equal(boot({saved:c.export()}).get().pending,null);const s=c.get();c.result({roundId:s.roundId,token:s.pending.token,kind:'ad_close',isEnded:true});const restored=boot({saved:c.export()});assert.ok(restored.apply().ok);assert.equal(restored.metrics().videoRequests,1);});
test('product: getter mutation does not modify authoritative state',()=>{const c=boot(),s=c.get();s.used.undo=9;assert.equal(c.get().used.undo,0);});
test('product: explicit shuffle permutation persists across grant failure retry',()=>{const c=boot({nextU32:()=>7});c.offer('shuffle','video');c.launch();const s=c.get(),p=s.pending.permutation;c.result({roundId:s.roundId,token:s.pending.token,kind:'ad_close',isEnded:true});c.failApplication();assert.ok(c.apply().ok);assert.deepEqual(c.get().board.deal.cells.map(t=>t.type),p);assert.equal(c.metrics().videoRequests,1);});
test('product: full fixture can clear through real commands',()=>{const c=boot();for(let i=0;i<10;i++)for(const j of [i,i+10,i+20])assert.ok(c.pick('t'+j).ok);assert.equal(c.get().board.status,'WON');assert.equal(R.restore(c.export()).state.board.cleared,30);});
test('product: video and share never receive separate quotas',()=>{const c=boot();c.pick('t0');earn(c,'undo');c.pick('t1');assert.equal(c.offer('undo','share').code,'ASSIST_EXHAUSTED');});
test('clock: overlapping pause reasons count active time only',()=>{assert.equal(typeof Clock.createClock,'function','clock missing');let now=0;const c=Clock.createClock(()=>now);c.start();now=100;c.pause('ad');now=200;c.pause('hidden');now=300;c.resume('ad');now=400;c.resume('hidden');now=500;assert.equal(c.elapsed(),200);});
test('clock: reset cannot inherit previous pause reasons',()=>{let now=0;const c=Clock.createClock(()=>now);c.start();c.pause('modal');c.reset();c.start();now=20;assert.equal(c.elapsed(),20);});
module.exports={fixture};
