'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const API=fs.existsSync(path.join(__dirname,'../services/server.js'))?require('../services/server'):{};
const deal=require('../examples/deal-270.json'),receipt=require('../examples/deal-270.receipt.json');
async function setup(t){assert.equal(typeof API.createServer,'function','HTTP module missing');const server=API.createServer({deals:[deal],persist:false});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const url='http://127.0.0.1:'+server.address().port;const req=async(p,body,token)=>{const r=await fetch(url+p,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};return {url,req};}
test('HTTP: explicit development login and actual shared service bootstrap',async t=>{const {req}=await setup(t),login=await req('/api/login',{deviceId:'one'});assert.equal(login.status,200);const r=await req('/api/call',{action:'bootstrap'},login.body.token);assert.equal(r.body.data.totals.wins,0);});
test('HTTP: no token, forged tokens and foreign origins rejected',async t=>{const {url,req}=await setup(t);assert.equal((await req('/api/call',{action:'bootstrap'})).status,401);assert.equal((await req('/api/call',{action:'bootstrap'},'fake')).status,401);const r=await fetch(url+'/api/login',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{"deviceId":"one"}'});assert.equal(r.status,403);});
test('HTTP: real ticket, replayed 270-click win, duplicate settlement',async t=>{const {req}=await setup(t),login=await req('/api/login',{deviceId:'one'}),token=login.body.token;const b=await req('/api/call',{action:'start',data:{mode:'daily'}},token);const {ticket,deal:d}=b.body.data;const c=require('../src/product/controller').createController(d,{roundId:ticket.id});for(const id of receipt.witness)assert.ok(c.pick(id).ok);const body={action:'settle',data:{ticketId:ticket.id,log:c.export(),elapsedMs:0}};assert.equal((await req('/api/call',body,token)).body.data.replayed,false);assert.equal((await req('/api/call',body,token)).body.data.replayed,true);});
test('HTTP: static service cannot serve project files or traversal',async t=>{const {url}=await setup(t);assert.equal((await fetch(url+'/package.json')).status,404);assert.equal((await fetch(url+'/%2e%2e%2fpackage.json')).status,404);});
test('HTTP: bad JSON rejected; mode cannot silently become production',async t=>{const {url}=await setup(t);assert.equal((await fetch(url+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:'not-json'})).status,400);assert.throws(()=>API.createServer({deals:[deal],mode:'production'}),/PRODUCTION/);});
