'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const modulePath=path.join(__dirname,'../ui/product/mascot.js');
const API=fs.existsSync(modulePath)?require(modulePath):{};
function mascot(options={}){assert.equal(typeof API.createMascot,'function','Canvas mascot API is missing');return API.createMascot(options);}
function canvas(){const calls=[],stack=[];const c={globalAlpha:.7,save(){stack.push(this.globalAlpha);calls.push(['save']);},restore(){this.globalAlpha=stack.pop();calls.push(['restore']);}};for(const name of ['beginPath','moveTo','lineTo','bezierCurveTo','quadraticCurveTo','closePath','clip','fill','stroke','translate','rotate','scale','drawImage','arc'])c[name]=(...args)=>calls.push([name,...args]);return {c,calls,stack};}
function artwork(){const image={width:1213,height:1296},asset={image,width:1213,height:1296,rect:{x:0,y:0,w:1213,h:1296}};return {image,asset,artAssets:{get:key=>key==='character.reference'?asset:null}};}

test('mascot: approved PNG is shipped byte-identical and gets an additive asset key',()=>{const p=path.join(__dirname,'../assets/theme/mascot/reference-cutout-v1.png');assert.ok(fs.existsSync(p),'approved carrot PNG is missing');const bytes=fs.readFileSync(p);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),'6910ee1d6b7bf7fc3a3e2f093dfe86fdd4b8d90a162fc37efcdf09c3e724c5bc');const manifest=require('../assets/theme/manifest.json');assert.equal(manifest.assets['character.reference'].src,'assets/theme/mascot/reference-cutout-v1.png');});
test('mascot: breath, leaf sway and blink preserve the approved neutral origin',()=>{const m=mascot();const initial=m.pose();assert.deepEqual(initial.bodyScale,{x:1,y:1});assert.equal(initial.blink,0);m.advance(.7);assert.notDeepEqual(m.pose().bodyScale,initial.bodyScale);assert.notEqual(m.pose().leafRotation,0);m.cancelAndSnap();m.advance(3.11);assert.ok(m.pose().blink>.99);});
test('mascot: lower priority taps cannot interrupt terminal performances',()=>{const m=mascot();assert.equal(m.play('win'),true);m.advance(.1);assert.equal(m.play('tap'),false);assert.equal(m.pose().cue,'win');m.advance(2);assert.equal(m.pose().expression,'win');assert.equal(m.play('tap'),true);assert.equal(m.play('bogus'),false);});
test('mascot: reduced motion immediately snaps and freezes existing and newly triggered cues',()=>{const m=mascot();m.play('win');m.advance(.25);m.setReducedMotion(true);const p=m.pose();assert.deepEqual(p.bodyScale,{x:1,y:1});assert.equal(p.offset.y,0);assert.equal(p.leafRotation,0);assert.equal(p.blink,0);assert.equal(p.particles,0);m.advance(30);assert.deepEqual(m.pose(),p);m.play('fail');assert.equal(m.pose().expression,'fail');assert.equal(m.pose().rotation,0);m.setReducedMotion(false);assert.equal(m.pose().active,false,'old terminal cue must not replay');});
test('mascot: hidden views do not advance animation or paint',()=>{const m=mascot();m.play('revive');m.advance(.1);m.setVisible(false);const p=m.pose();m.advance(20);assert.deepEqual(m.pose(),p);const {c,calls}=canvas();assert.equal(m.draw(c,0,0,100,100),false);assert.deepEqual(calls,[]);m.setVisible(true);m.advance(.1);assert.notDeepEqual(m.pose(),p);});
test('mascot: committed events are read-only, revision-deduplicated and revive replaces fail',()=>{const m=mascot(),state=Object.freeze({roundId:'r1',revision:1}),events=Object.freeze([Object.freeze({type:'TAKE'}),Object.freeze({type:'CLEAR'}),Object.freeze({type:'WON'})]);assert.equal(m.consumeCommitted(state,events),'win');m.advance(.2);const p=m.pose();assert.equal(m.consumeCommitted(state,events),null);assert.deepEqual(m.pose(),p);m.play('fail');assert.equal(m.consumeCommitted(Object.freeze({roundId:'r1',revision:2}),Object.freeze([Object.freeze({type:'REVIVE_CANDIDATE_APPLIED'})])),'revive');assert.equal(m.pose().expression,'idle');assert.equal(m.pose().cue,'revive');assert.equal(m.consumeCommitted({roundId:'',revision:1},events),null);});
test('mascot: bad deltas are ignored and returned poses cannot mutate the rig',()=>{const m=mascot(),before=m.pose();for(const delta of [NaN,Infinity,-1,'2'])m.advance(delta);assert.deepEqual(m.pose(),before);const p=m.pose();p.bodyScale.x=999;p.offset.y=20;assert.deepEqual(m.pose(),before);});
test('mascot: Canvas fallback uses the exact source image, no SVG or Path2D, and restores state',()=>{const pack=artwork(),m=mascot({artAssets:pack.artAssets,createCanvas:()=>null}),{c,calls,stack}=canvas();assert.equal(m.draw(c,10,20,160,180,{skin:'cap',role:'home'}),true);const images=calls.filter(c=>c[0]==='drawImage');assert.ok(images.length>=2);assert.ok(images.every(c=>c[1]===pack.image));assert.ok(calls.some(c=>c[0]==='clip'),'leaf and body use runtime masks');assert.equal(c.globalAlpha,.7);assert.equal(stack.length,0);});
test('mascot: fail and blink overlays retain source-based color and reject unavailable images safely',()=>{const pack=artwork(),m=mascot({artAssets:pack.artAssets,createCanvas:()=>null}),{c,calls}=canvas();m.cancelAndSnap('fail');assert.equal(m.draw(c,0,0,160,180,{skin:'scarf',role:'first'}),true);assert.ok(calls.filter(c=>c[0]==='drawImage').length>2,'facial cover must sample the original orange surface');const missing=mascot(),empty=canvas();assert.equal(missing.draw(empty.c,0,0,100,100),false);assert.deepEqual(empty.calls,[]);assert.equal(m.draw(c,NaN,0,10,10),false);});
test('mascot: a fully closed blink covers the original eyes through their lower white edges',()=>{const pack=artwork(),m=mascot({artAssets:pack.artAssets,createCanvas:()=>null}),{c,calls}=canvas();m.advance(3.11);m.draw(c,0,0,1213,1296);assert.ok(calls.some(v=>v[0]==='lineTo'&&v[1]===1213&&v[2]>=1296*.69&&v[2]<1296*.71),'closed eyelid must reach below the original white eyes');});
test('mascot: fallback sad mouth erase stays inside the source mouth silhouette',()=>{const pack=artwork(),m=mascot({artAssets:pack.artAssets,createCanvas:()=>null}),{c,calls}=canvas();m.cancelAndSnap('fail');m.draw(c,0,0,1213,1296);assert.ok(!calls.some(v=>v[0]==='lineTo'&&v[1]===1213*.68&&v[2]===1296*.95),'a rectangular erase projects outside the original body at its bottom corners');});
test('mascot: fallback erases underlying mouth ink before sampling semitransparent orange pixels',()=>{const pack=artwork(),m=mascot({artAssets:pack.artAssets,createCanvas:()=>null}),{c,calls}=canvas();m.cancelAndSnap('fail');m.draw(c,0,0,1213,1296);const at=calls.findIndex(v=>v[0]==='drawImage'&&v[2]===1213*.255);assert.ok(at>=0);assert.equal(calls[at-1][0],'fill','original orange alpha is 253/255 and cannot erase old ink alone');});
