'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const UI=fs.existsSync(path.join(__dirname,'../ui/product/app.js'))?require('../ui/product/app'):{};
const deal=require('../examples/deal-270.json'),receipt=require('../examples/deal-270.receipt.json');
const context=new Proxy({measureText:t=>({width:String(t).length*7})},{get:(o,k)=>k in o?o[k]:()=>{}});
async function boot(deals=[deal]){assert.equal(typeof UI.createFullApp,'function','complete UI missing');const app=UI.createFullApp({getContext:()=>context},deals,390,844,1,{motion:false});await app.ready;return app;}
async function click(app,id){const r=app.getHitRegions().find(x=>x.id===id);assert.ok(r,'missing button '+id);assert.ok(r.enabled,'disabled '+id);return app.tap(r.x+r.w/2,r.y+r.h/2);}
test('UI: all homepage entrypoints lead to real navigable panels',async()=>{const a=await boot();assert.equal(a.getScene(),'HOME');for(const name of ['rank','friends','topic','wardrobe','profile','bullet','club','settings','honor-first','honor-king','honor-fast']){await click(a,name);assert.ok(a.getModal(),name);await click(a,'close');assert.equal(a.getModal(),null);}});
test('UI: tutorial transitions directly to the daily board',async()=>{const a=await boot();await click(a,'start');assert.equal(a.getState().board.deal.cells.length,12);for(let i=0;i<12;i++)await a.qa.pick('teach-'+i);assert.equal(a.getModal(),'TUTORIAL_WIN');await click(a,'next-daily');assert.equal(a.getState().board.deal.cells.length,270);});
test('UI: settings never change the running deal and quota',async()=>{const a=await boot();await a.qa.start('daily');const before=a.getState();await click(a,'settings');await click(a,'setting-sound');await click(a,'close');assert.deepEqual(a.getState(),before);});
test('UI: video/move/grant changes the actual board',async()=>{const a=await boot();await a.qa.start('daily');for(const id of receipt.witness.slice(0,3))await a.qa.pick(id);await click(a,'move');assert.equal(a.getModal(),'OFFER');await click(a,'grant');assert.equal(a.getModal(),'PROVIDER');await click(a,'dev-complete');assert.equal(a.getState().board.buffer.length,3);assert.equal(a.getState().used.move,1);});
test('UI: actual completed deal shows win and local contribution',async()=>{const a=await boot();await a.qa.start('daily');for(const id of receipt.witness)await a.qa.pick(id);assert.equal(a.getState().board.status,'WON');assert.equal(a.getModal(),'WIN');assert.equal(a.getInfo().totals.wins,1);await click(a,'return-home');assert.equal(a.getScene(),'HOME');});
test('UI: all responsive interactive targets stay inside the canvas',async()=>{const a=await boot();for(const [w,h] of [[320,568],[390,844],[430,932],[460,720]]){a.resize(w,h,2);for(const name of ['rank','friends','topic','wardrobe','settings']){await click(a,name);for(const r of a.getHitRegions()){assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=w+.01&&r.y+r.h<=h+.01,JSON.stringify(r));}await click(a,'close');}}});
test('UI: invalid touch values cannot affect a round',async()=>{const a=await boot();await a.qa.start('daily');const s=a.getState();await a.tap(NaN,0);await a.tap(Infinity,20);assert.deepEqual(a.getState(),s);});
test('UI: cancelled reward removes provider overlay without dereferencing old flow',async()=>{const a=await boot();await a.qa.start('daily');await a.qa.pick(receipt.witness[0]);await click(a,'undo');await click(a,'grant');await click(a,'dev-cancel');assert.equal(a.getModal(),null);assert.equal(a.getState().used.undo,0);});
test('UI: tutorial cards leave space for the reserve label on all screen sizes',async()=>{const a=await boot();await click(a,'start');for(const [w,h] of [[320,568],[390,844],[430,932],[460,720]]){a.resize(w,h,2);const scale=w/390,reserveY=h-237*scale;const cells=a.getHitRegions().filter(r=>r.kind==='tile'&&r.zone!=='buffer');assert.ok(cells.every(r=>r.y+r.h<=reserveY-32*scale),'cards crowd reserve label at '+w+'x'+h);}});
test('UI: local history pagination never skips records',async()=>{const base=await boot(),info=base.getInfo();info.history.records=Array.from({length:18},(_,i)=>({day:'record-'+i,mode:'daily',status:'WON'}));const shown=new Set();const context2=new Proxy({measureText:t=>({width:String(t).length*7}),fillText:t=>{if(String(t).startsWith('record-'))shown.add(t);}},{get:(o,k)=>k in o?o[k]:()=>{}});const a=UI.createFullApp({getContext:()=>context2},[deal],390,844,1,{motion:false,client:{kind:'local',scope:'test',request:async()=>info}});await a.ready;await click(a,'friends');await click(a,'history');for(let i=0;i<10;i++){const next=a.getHitRegions().find(r=>r.id==='page-next');if(!next.enabled)break;await click(a,'page-next');}assert.equal(shown.size,18);});
test('UI: native safe-area and menu inset never receive gameplay controls',async()=>{const a=UI.createFullApp({getContext:()=>context},[deal],375,667,2,{motion:false,insets:{top:88,bottom:25}});await a.ready;await click(a,'start');for(const r of a.getHitRegions())assert.ok(r.y>=88&&r.y+r.h<=642+.01,JSON.stringify(r));});
test('UI: short displays keep home controls disjoint and inside the canvas',async()=>{const a=await boot();a.resize(390,550,2);const rs=a.getHitRegions().filter(r=>r.enabled);for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const x=rs[i],y=rs[j],intersection=Math.min(x.x+x.w,y.x+y.w)>Math.max(x.x,y.x)&&Math.min(x.y+x.h,y.y+y.h)>Math.max(x.y,y.y);assert.equal(intersection,false,x.id+' overlaps '+y.id);}for(const r of rs)assert.ok(r.y>=0&&r.y+r.h<=550,JSON.stringify(r));});
