'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createFullApp}=require('../ui/product/app');
const deal={schema:'astra-deal-1',dealId:'presentation-three',layoutId:'open',origin:'SYNTHETIC_NOT_HISTORICAL',slotCapacity:7,cells:Array.from({length:3},(_,i)=>({id:'v'+i,type:'T00',zone:'board',z:0,rect:{x:i*100,y:0,w:96,h:96}}))};
const context=new Proxy({measureText:t=>({width:String(t).length*7})},{get:(o,k)=>k in o?o[k]:()=>{}});
async function boot(motion=true){let time=Date.UTC(2026,9,2,6);const app=createFullApp({getContext:()=>context},[deal],390,844,1,{now:()=>time,motion});await app.ready;await app.qa.start('daily');return {app,advance:ms=>{time+=ms;app.frame();}};}
function target(app,id){const r=app.getHitRegions().find(r=>r.id===id);assert.ok(r,id);return [r.x+r.w/2,r.y+r.h/2];}
test('presentation: pointer press does not act until release and cancelling keeps board intact',async()=>{const {app}=await boot(false),before=app.getState();app.pointerDown(...target(app,'tile:v0'),1);assert.deepEqual(app.getState(),before);app.pointerCancel(1);await app.pointerUp(...target(app,'tile:v0'),1);assert.deepEqual(app.getState(),before);app.pointerDown(...target(app,'tile:v0'),2);await app.pointerUp(...target(app,'tile:v0'),2);assert.equal(app.getState().board.rack.length,1);});
test('presentation: last three tiles settle immediately but finish clearing before win overlay',async()=>{const {app,advance}=await boot();for(const id of ['v0','v1']){await app.tap(...target(app,'tile:'+id));advance(500);}await app.tap(...target(app,'tile:v2'));assert.equal(app.getState().board.status,'WON');assert.equal(app.getInfo().totals.wins,1,'settlement must not wait for animation');assert.equal(app.getModal(),null,'last clear is obscured');advance(800);assert.equal(app.getModal(),'WIN');});
test('presentation: reduced motion immediately shows terminal overlay',async()=>{const {app}=await boot(false);for(const id of ['v0','v1','v2'])await app.tap(...target(app,'tile:'+id));assert.equal(app.getModal(),'WIN');});
test('presentation: hiding cancels pressed target and resize cancels stale pointer',async()=>{const {app}=await boot(false);app.pointerDown(...target(app,'tile:v0'),1);await app.setVisible(false);await app.setVisible(true);await app.pointerUp(...target(app,'tile:v0'),1);assert.equal(app.getState().board.rack.length,0);app.pointerDown(...target(app,'tile:v0'),2);app.resize(320,568,1);await app.pointerUp(...target(app,'tile:v0'),2);assert.equal(app.getState().board.rack.length,0);});
test('presentation: compact side stacks show exactly the actual legal front tile',async()=>{const original=require('../examples/deal-720.json'),app=createFullApp({getContext:()=>context},[original],390,844,1,{motion:false});await app.ready;await app.qa.start('daily');const before=app.getState(),rs=app.getHitRegions().filter(r=>r.kind==='tile'&&r.zone==='side'&&r.enabled);assert.equal(rs.length,2);for(const r of rs)assert.equal(before.board.blockers[before.board.byId[r.tileId]],0);await app.tap(...target(app,rs[0].id));const after=app.getHitRegions().filter(r=>r.kind==='tile'&&r.zone==='side'&&r.enabled);assert.equal(after.length,2);assert.ok(after.every(r=>r.tileId!==rs[0].tileId));});
