'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const modulePath=path.join(__dirname,'../ui/product/icons.js'),API=fs.existsSync(modulePath)?require(modulePath):{};
const names=['back','settings','close','move','undo','shuffle','revive','rank','friends','topic','wardrobe','profile','club','locate','bullet','volume','mute','music','eye','eye_off'];
function canvas(){const calls=[];const c={};for(const name of ['save','restore','translate','scale','beginPath','moveTo','lineTo','bezierCurveTo','quadraticCurveTo','closePath','fill'])c[name]=(...args)=>calls.push([name,...args]);return {c,calls};}

test('icons: all 20 approved Phosphor icons paint with portable Canvas commands',()=>{assert.equal(typeof API.drawIcon,'function','portable Phosphor renderer is missing');for(const name of names){const {c,calls}=canvas();assert.equal(API.drawIcon(c,name,25,30,24,'#254332'),true,name);assert.deepEqual(calls[0],['save']);assert.deepEqual(calls.at(-1),['restore']);assert.ok(calls.some(c=>c[0]==='fill'),name);assert.ok(calls.some(c=>c[0]==='bezierCurveTo'||c[0]==='lineTo'),name);}const {c,calls}=canvas();assert.equal(API.drawIcon(c,'sound',0,0),true);assert.ok(calls.length>0);});
test('icons: invalid names and geometry leave Canvas untouched',()=>{assert.equal(typeof API.drawIcon,'function');for(const args of [['not-icon',1,2,24],['back',NaN,2,24],['back',1,2,0],['back',1,2,-5]]){const {c,calls}=canvas();assert.equal(API.drawIcon(c,...args),false);assert.deepEqual(calls,[]);}});
test('icons: source files preserve Phosphor attribution and exact approved SVG hashes',()=>{const dir=path.join(__dirname,'../assets/theme/phosphor');assert.ok(fs.existsSync(path.join(dir,'LICENSE')),'MIT license is missing');assert.match(fs.readFileSync(path.join(dir,'LICENSE'),'utf8'),/Copyright \(c\) 2023 Phosphor Icons/);const hashes=JSON.parse(fs.readFileSync(path.join(dir,'sha256.json'),'utf8'));assert.equal(hashes.length,20);for(const file of hashes){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,file.file))).digest('hex'),file.local_sha256,file.file);}});
test('icons: offline compiler reproduces shipped portable paths without network dependencies',()=>{const script=path.join(__dirname,'../assets/theme/phosphor/compile.js');assert.ok(fs.existsSync(script),'offline compiler is missing');const result=cp.spawnSync(process.execPath,[script,'--check'],{encoding:'utf8'});assert.equal(result.status,0,result.stderr||result.stdout);});
test('icons: object prototype names are not valid drawing commands',()=>{assert.equal(typeof API.drawIcon,'function');for(const name of ['__proto__','constructor','toString']){const {c,calls}=canvas();assert.equal(API.drawIcon(c,name,0,0,24),false);assert.deepEqual(calls,[]);}});
