'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const S=fs.existsSync(path.join(__dirname,'../src/product/social.js'))?require('../src/product/social'):{};
const C=fs.existsSync(path.join(__dirname,'../src/product/controller.js'))?require('../src/product/controller'):{};
const deal={schema:'astra-deal-1',dealId:'social-fixture',layoutId:'open',origin:'SYNTHETIC_NOT_HISTORICAL',slotCapacity:7,cells:[...'ABCABCABC'].map((type,i)=>({id:'t'+i,type,zone:'board',z:0,rect:{x:i%3*100,y:Math.floor(i/3)*100,w:96,h:96}}))};
function make(options={}){assert.equal(typeof S.createSocial,'function','social module missing');let now=Date.UTC(2026,8,18,4);return {service:S.createSocial({deals:[deal],now:()=>now,...options}),advance:ms=>now+=ms};}
function win(service,user='local',mode='daily'){const {ticket,deal:d}=service.call(user,'start',{mode});const c=C.createController(d,{roundId:ticket.id});for(const id of ['t0','t3','t6','t1','t4','t7','t2','t5','t8'])assert.ok(c.pick(id).ok);return {ticketId:ticket.id,log:c.export(),elapsedMs:0};}
test('social: first bootstrap has zero synthetic population and no currency',()=>{const {service}=make(),s=service.call('local','bootstrap');assert.equal(s.totals.wins,0);assert.equal(s.profile.skin,'plain');assert.equal(s.profile.coin,undefined);assert.equal(s.dataMode,'development_local');});
test('social: validated clear adds region contribution once',()=>{const {service}=make();const data=win(service);const a=service.call('local','settle',data),b=service.call('local','settle',data);assert.equal(a.result.status,'WON');assert.equal(b.replayed,true);assert.equal(service.call('local','bootstrap').totals.wins,1);});
test('social: two full clears on same day never add a second sheep',()=>{const {service}=make();service.call('local','settle',win(service));service.call('local','settle',win(service));assert.equal(service.call('local','bootstrap').totals.wins,1);});
test('social: a ticket cannot be settled by another user',()=>{const {service}=make(),d=win(service);assert.throws(()=>service.call('other','settle',d),/TICKET_OWNER/);});
test('social: nonterminal and altered deal logs cannot claim wins',()=>{const {service}=make();const {ticket,deal:d}=service.call('local','start',{mode:'daily'});const c=C.createController(d,{roundId:ticket.id});assert.throws(()=>service.call('local','settle',{ticketId:ticket.id,log:c.export(),elapsedMs:0}),/NOT_TERMINAL/);});
test('social: replay checksum does not replace assigned-deal verification',()=>{const {service}=make();const {ticket}=service.call('local','start',{mode:'daily'});const d=JSON.parse(JSON.stringify(deal));d.dealId='forged';const c=C.createController(d,{roundId:ticket.id});for(const id of ['t0','t3','t6','t1','t4','t7','t2','t5','t8'])c.pick(id);assert.throws(()=>service.call('local','settle',{ticketId:ticket.id,log:c.export(),elapsedMs:0}),/DEAL_MISMATCH/);});
test('social: negative or impossible duration rejected',()=>{const {service}=make(),d=win(service);assert.throws(()=>service.call('local','settle',{...d,elapsedMs:-1}),/INVALID_DURATION/);assert.throws(()=>service.call('local','settle',{...d,elapsedMs:1e8}),/INVALID_DURATION/);});
test('social: an expired ticket cannot update the new day',()=>{const {service,advance}=make(),d=win(service);advance(86400000);assert.throws(()=>service.call('local','settle',d),/CYCLE_EXPIRED/);assert.equal(service.call('local','bootstrap').totals.wins,0);});
test('social: daily and topic contributions are separate',()=>{const {service}=make();service.call('local','settle',win(service));service.call('local','settle',win(service,'local','topic'));const b=service.call('local','bootstrap');assert.equal(b.totals.wins,1);assert.equal(b.topic.scores.reduce((a,b)=>a+b,0),1);});
test('social: topic assignment is stable within the same cycle',()=>{const {service}=make();assert.equal(service.call('local','bootstrap').topic.team,service.call('local','bootstrap').topic.team);});
test('social: locked appearance cannot be equipped',()=>{const {service}=make();assert.throws(()=>service.call('local','equip',{skin:'cap'}),/SKIN_LOCKED/);});
test('social: clearing unlocks and equips development appearance without stats',()=>{const {service}=make();service.call('local','settle',win(service));service.call('local','equip',{skin:'cap'});const p=service.call('local','bootstrap').profile;assert.equal(p.skin,'cap');assert.ok(p.owned.includes('cap'));assert.equal(p.attack,undefined);});
test('social: only preset bullets, never arbitrary message input',()=>{const {service}=make();assert.throws(()=>service.call('local','bullet',{text:'spam'}),/INVALID_BULLET/);const r=service.call('local','bullet',{id:'cheer'});assert.equal(r.bullets.length,1);});
test('social: old rank data is not carried into a new cycle',()=>{const {service,advance}=make();service.call('local','settle',win(service));advance(86400000);const b=service.call('local','bootstrap');assert.equal(b.totals.wins,0);assert.equal(b.history.wins,1);assert.equal(b.honors.first.userId,'local');});
test('social: storage failure leaves stats unchanged and settlement retryable',()=>{let fail=false;const {service}=make({save(){if(fail)throw Error('disk fail');}});const d=win(service);fail=true;assert.throws(()=>service.call('local','settle',d),/disk fail/);fail=false;assert.equal(service.call('local','bootstrap').totals.wins,0);assert.equal(service.call('local','settle',d).replayed,false);});
test('social: persisted data survives a service restart',()=>{let text;const {service}=make({save:v=>text=v});service.call('local','settle',win(service));const other=make({initial:text});assert.equal(other.service.call('local','bootstrap').totals.wins,1);});
test('social: invalid user IDs and unknown actions are rejected',()=>{const {service}=make();assert.throws(()=>service.call('__proto__','bootstrap'),/INVALID_USER/);assert.throws(()=>service.call('local','buy'),/UNKNOWN_ACTION/);});
test('social: tutorial completion updates tutorial flag without rank rewards',()=>{const {service}=make();const {ticket,deal:d}=service.call('local','start',{mode:'tutorial'});const c=C.createController(d,{roundId:ticket.id});for(const tile of d.cells)c.pick(tile.id);assert.equal(c.get().board.status,'WON');service.call('local','settle',{ticketId:ticket.id,log:c.export(),elapsedMs:0});const b=service.call('local','bootstrap');assert.equal(b.profile.tutorialDone,true);assert.equal(b.totals.wins,0);});
test('social: malformed persistence fails closed rather than deleting data',()=>{assert.throws(()=>make({initial:'bad'}),/INVALID_SOCIAL_SAVE/);});
