'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const native=path.join(__dirname,'../templates/wechat-full/game.js');
function context(texts=[]){return new Proxy({measureText:t=>({width:String(t).length*7}),fillText:t=>texts.push(String(t))},{get:(o,k)=>k in o?o[k]:()=>{}});}
async function bootstrap(){const listeners={},saved=new Map(),cv={getContext:()=>context()},wx={createCanvas:()=>cv,getWindowInfo:()=>({windowWidth:375,windowHeight:667,pixelRatio:2,safeArea:{top:44,bottom:642}}),getMenuButtonBoundingClientRect:()=>({top:48,bottom:80}),getStorageSync:k=>saved.get(k),setStorageSync:(k,v)=>saved.set(k,v),onTouchStart:f=>listeners.touch=f,onShow:f=>listeners.show=f,onHide:f=>listeners.hide=f,onWindowResize:f=>listeners.resize=f};const sandbox={wx,requestAnimationFrame:()=>{},require:createRequire(path.join(__dirname,'../wechat_full/game.js')),module:{exports:{}},console};vm.runInNewContext(fs.readFileSync(native,'utf8')+'\nmodule.exports=app;',sandbox,{filename:'native-game.js'});const app=sandbox.module.exports;await app.ready;return {app,listeners,cv};}
test('native entry: boot and menu/safe-area offset affect real hit regions',async()=>{const {app,cv}=await bootstrap();assert.equal(app.getScene(),'HOME');assert.equal(cv.width,750);for(const r of app.getHitRegions())assert.ok(r.y>=88&&r.y+r.h<=642+.01,JSON.stringify(r));});
test('native entry: lifecycle gates real touch events',async()=>{const {app,listeners}=await bootstrap();listeners.hide();let r=app.getHitRegions().find(r=>r.id==='start');listeners.touch({touches:[{clientX:r.x+r.w/2,clientY:r.y+r.h/2}]});await new Promise(r=>setImmediate(r));assert.equal(app.getScene(),'HOME');listeners.show();await new Promise(r=>setImmediate(r));r=app.getHitRegions().find(r=>r.id==='start');listeners.touch({touches:[{clientX:r.x+r.w/2,clientY:r.y+r.h/2}]});await new Promise(r=>setImmediate(r));assert.equal(app.getScene(),'PLAY');});
function domain(){let callback,requests=[],texts=[];const canvas={width:320,height:400,getContext:()=>context(texts)};const api=require('../templates/wechat-full/open-data/renderer');const controller=api.installOpenData({getSharedCanvas:()=>canvas,onMessage:f=>callback=f,getFriendCloudStorage:o=>requests.push(o)});return {controller,requests,texts,message:m=>callback(m)};}
test('native friends: invalid dimensions and irrelevant messages never request cloud data',()=>{const d=domain();d.message({type:'SHOW_FRIENDS',width:1e9,height:300});d.message({type:'else'});assert.equal(d.requests.length,0);});
test('native friends: stale callbacks cannot redraw a hidden panel',()=>{const d=domain();d.message({type:'SHOW_FRIENDS',width:320,height:400,day:'2026-09-18'});d.message({type:'HIDE_FRIENDS'});const n=d.texts.length;d.requests[0].success({data:[{nickname:'STALENAME',KVDataList:[]}]});assert.equal(d.texts.length,n);});
test('native friends: only requested current day and history are rendered',()=>{const d=domain();d.message({type:'SHOW_FRIENDS',width:320,height:400,day:'2026-09-18'});d.requests[0].success({data:[{nickname:'好友甲',KVDataList:[{key:'sheep_dev_today',value:JSON.stringify({day:'2026-09-17',win:true})},{key:'sheep_dev_history',value:'bad json'}]}]});assert.ok(d.texts.some(t=>t.includes('好友甲')));assert.ok(d.texts.some(t=>t==='今日失败 0 次'));assert.equal(d.texts.includes('今日已通关'),false);});
