'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Art=require('../ui/product/art');
function canvas(){const paths=[];const ctx=new Proxy({globalAlpha:1,beginPath:()=>paths.push('path')},{get:(o,k)=>k in o?o[k]:()=>{}});return {ctx,paths};}
test('art renderer: an available frame and symbol replace the complete old tile drawing',()=>{const {ctx,paths}=canvas(),keys=[],render=Art.withAssets({draw:(c,key)=>{keys.push(key);return true;}});render.tile(ctx,'T00',0,0,48,48);assert.deepEqual(keys,['tile.frame','tile.T00']);assert.equal(paths.length,0,'old plate or shadow must not survive a complete replacement');});
test('art renderer: independently unavailable plate and symbol keep the current drawing',()=>{const {ctx,paths}=canvas(),render=Art.withAssets({draw:()=>false});render.tile(ctx,'T00',0,0,48,48);assert.ok(paths.length>=3,'missing images must not make a blank tile');});
test('art renderer: character and grave images replace their respective drawings',()=>{const {ctx,paths}=canvas(),keys=[],render=Art.withAssets({draw:(c,key)=>{keys.push(key);return true;}});render.sheep(ctx,80,80,70,'cap');render.tomb(ctx,80,80,60);assert.deepEqual(keys,['character.cap','character.grave']);assert.equal(paths.length,0);});
test('art renderer: classic tile icons fill at least four fifths of the face with clear bottom-lip space',()=>{const {ctx}=canvas(),draws=[],render=Art.withAssets({draw:(c,key,x,y,w,h)=>{draws.push({key,x,y,w,h});return true;}});render.tile(ctx,'T00',10,20,48,48);const glyph=draws.find(d=>d.key==='tile.T00');assert.ok(glyph.w>=38.4&&glyph.h>=38.4,'glyph remains a small sticker on a large plate');assert.ok(glyph.x>10&&glyph.x+glyph.w<58,'glyph must stay inside the front face');assert.ok(glyph.y>20&&glyph.y+glyph.h<65,'glyph must not cover the bottom thickness');});
test('art renderer: covered tiles keep both image layers opaque and use a dark surface overlay',()=>{const paths=[],fills=[],stack=[],ctx=new Proxy({globalAlpha:.8,beginPath:()=>paths.push('path'),save(){stack.push({globalAlpha:this.globalAlpha,fillStyle:this.fillStyle});},restore(){Object.assign(this,stack.pop());},fill(){fills.push({color:this.fillStyle,alpha:this.globalAlpha});}},{get:(o,k)=>k in o?o[k]:()=>{}}),alphas=[],render=Art.withAssets({draw:(c,key)=>{alphas.push(c.globalAlpha);return true;}});render.tile(ctx,'T00',0,0,48,48,false);assert.deepEqual(alphas,[.8,.8],'covered art must not reveal landscape through the card');assert.ok(fills.some(f=>/^rgba\(/.test(f.color)),'covered card must have a visible dark mask');assert.equal(ctx.globalAlpha,.8,'tile must preserve inherited animation alpha');});
